# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG NODE_VERSION=20
FROM node:${NODE_VERSION}-alpine AS build-env

WORKDIR /usr/src/app
COPY src/autoscaler-common/ src/autoscaler-common/
COPY src/scaler/ src/scaler/
COPY package*.json ./
RUN npm config set update-notifier false
RUN npm install --omit=dev
RUN find /usr/src/app/ -type d -exec chmod a+x '{}' ';'
RUN find /usr/src/app/ -type f -name '*.js*' -exec chmod a+r '{}' ';'

FROM gcr.io/distroless/nodejs${NODE_VERSION}:nonroot
COPY --from=build-env /usr/src/app /usr/src/app
WORKDIR /usr/src/app/

CMD ["-e", "require('./src/scaler/index').main()"]
