# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG NODE_VERSION=20
FROM node:${NODE_VERSION}-alpine AS build-env

WORKDIR /usr/src/app
COPY autoscaler-common/ autoscaler-common/
COPY scaler/ scaler/

WORKDIR /usr/src/app/autoscaler-common
RUN npm config set update-notifier false
RUN npm install  --omit=dev

WORKDIR /usr/src/app/scaler
RUN npm install  --omit=dev

FROM gcr.io/distroless/nodejs${NODE_VERSION}:latest
COPY --from=build-env /usr/src/app /usr/src/app
WORKDIR /usr/src/app/scaler/scaler-core

CMD ["-e", "require('../index').main()"]
