name: Node.js unit tests

on: [push, pull_request]

jobs:
  test-poller:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: poller/poller-core

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true

  test-scaler:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scaler/scaler-core

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
